ci: Sort list of displayed jobs
zaquestion/lab pull request #514
Opened 2020-12-06 04:28 UTC by fmuellner

When we filter the list to only show the latest job of each stage+name
combo, we mess up the expected order of jobs in the pipeline.

Address this by sorting the filtered list before returning it.

Fixes https://github.com/zaquestion/lab/issues/471

2020-12-10 14:39 UTC, bmeneguele approved these changes

2020-12-10 14:43 UTC, bmeneguele requested changes
Actually, this change seems to be breaking the order of expected test results.
Could you take a look on both `Test_latestJobs` and `Test_ciStatus`?

2020-12-11 20:39 UTC, fmuellner commented
Updated:
 - code moved to CIJobs(), which on second thought seems a better place for sorting
 - reverted tests to their original order

2020-12-11 22:50 UTC, bmeneguele approved these changes

2020-12-13 20:52 UTC, merged