mr_create: Check for zero commits in a Merge Request
zaquestion/lab pull request #637
Opened 2021-03-16 00:23 UTC by prarit

It is possible to open up a Merge Request with zero commits by pushing a
branch with no changes and then executing 'lab mr create'.

lab should abort the creation of an MR in this case.

Check the number of commits in the remote branch, and if it is zero, abort
the creation of the Merge Request.

Signed-off-by: Prarit Bhargava <prarit@redhat.com>

2021-03-16 12:30 UTC, bmeneguele approved these changes
Changes are looking good to me.
Only thing is to correct the test code for the new git.Log() return values:  
`internal/git/git_test.go:76:18: assignment mismatch: 3 variables but Log returns 2 values`

2021-03-16 13:15 UTC, prarit commented
Yep.  I also have to fix the code to look at the remote source branch instead of the local source branch when calculating the change log and number of commits.  Hopefully this morning :)

2021-03-16 13:22 UTC, bmeneguele commented
Ah yes! well observed.

2021-03-17 11:33 UTC, prarit commented
Just updating the text in the commit descriptions.  Remaining work is to provide a test for 'lab mr create --source'.

2021-03-17 15:09 UTC, bmeneguele commented
@prarit, both `git.CurrentBranch` and `git.CurrentUpstreamBranch()` must take in consideration the `remote:branch` the user passed through args now.

https://github.com/zaquestion/lab/blob/a897827b36989c87b88020879aa50899b74e0c81/cmd/mr_create.go#L129-L133

The above snippet will check `remoteBranch` for its existence in the `sourceRemote`, which will fail if the user is checked out in a branch different from the one he passed through the args. For instance:
```
$ git remote
origin
upstream
$ git branch -vv
* 8.3              fc08cc6b47fb [upstream/8.3] test
genlog        07d8b29d4e25 [origin/genlog] [redhat] fix genlog.py for patches with single line changelog
main           dabd49203c52 [upstream/main] Merge branch '1872412' into 'main'
$ lab mr create --source origin:genlog-test upstream main
2021/03/17 12:01:47 mr_create.go:169: aborting MR, source branch 8.3 not present on remote origin. did you forget to push?: GET https://gitlab.com/api/v4/projects/21035236/repository/commits/8.3: 404 {message: 404 Commit Not Found}
```
I was checked out in branch `8.3`.

Another thing, but just cosmetics: could you also add a newline to the end of the messages being printed with `log.Wrapf()`? :D.

2021-03-17 16:28 UTC, prarit commented
>The above snippet will check remoteBranch for its existence in the sourceRemote, which will fail if the user is checked out in a branch different from the one he passed through the args. For instance:

Oh good catch.  And that becomes a good test case too!

2021-03-18 16:58 UTC, prarit commented
I am removing the --source option from this PR and will push it separately.  That way at least lab is working correctly and doesn't suffer from the brokenness I introduced :)

2021-03-18 17:21 UTC, bmeneguele requested changes

2021-03-18 17:21 UTC, bmeneguele commented on cmd/mr_create.go
> +	targetBase := fmt.Sprintf("%s/%s", sourceRemote, head)
May I kindly suggest that we change these names?
How does `remoteBase` relates to `targetRemote` while `targetBase` relates to `sourceRemote`?
It kinda messes with my head even knowing what the code does.

`base` here points to the target branch, so `remoteBase` could be `targetRef` or `targetBase`?
`head` is the source branch, so `targetBase` could be `sourceRef` or `sourceBase`?

2021-03-18 17:27 UTC, bmeneguele commented
@prarit, there still have one place you need to change:
```go
msg, err := mrText(targetBranch, branch, sourceRemote, targetRemote, coverLetterFormat)
```

The `branch` there should be `remoteBranch` instead, since the `branch` points to the local branch and ignores if it has an upstream branch name different from the local. For instance, if I `git push -u <remote> <local-branch-name>:<remote-branch-name>` the changes, in the MR EDIT message the `<local-branch-name>` will be used.

Since `remoteBranch` is being used for calculating the diff, it makes sense to also use its name in the MR EDIT text.

2021-03-18 17:57 UTC, prarit commented
> @prarit, there still have one place you need to change:
> 
> ```go
> msg, err := mrText(targetBranch, branch, sourceRemote, targetRemote, coverLetterFormat)
> ```
> 
> The `branch` there should be `remoteBranch` instead, since the `branch` points to the local branch and ignores if it has an upstream branch name different from the local. For instance, if I `git push -u <remote> <local-branch-name>:<remote-branch-name>` the changes, in the MR EDIT message the `<local-branch-name>` will be used.
> 
> Since `remoteBranch` is being used for calculating the diff, it makes sense to also use it in the MR EDIT text.

Good point.  I was running on the assumption that the local source branch name and remote source branch names are the same.  I'll fix that.

2021-03-18 18:59 UTC, bmeneguele approved these changes
Yep, LGTM now :))

2021-03-19 11:44 UTC, merged