Added documentation examples on every command; Fixes
zaquestion/lab pull request #717
Opened 2021-07-14 14:20 UTC by zampierilucas

Added example to every command;
Remove new-line after heredoc to avoid blank lines;
Fixed mr_create to show link only on creation success;
Added safeguard on issue_show if user does not specified issue number;
Removed --reply mention on examples in issue_note and mr_note, since it was a implementation
residue;

Signed-off-by: Lucas Zampieri <lzampier@redhat.com>

2021-07-21 13:09 UTC, prarit requested changes
@zampierilucas can you run your changes through 'git-show -ws-error-highlight=all'?  You'll see a bunch of whitespace issues at the end of lines.

2021-07-23 19:24 UTC, prarit approved these changes

2021-07-23 19:25 UTC, prarit commented
Just run "gofmt -d .", commit,  and resubmit the PR.  That will clean up the failed build.

2021-07-27 22:12 UTC, bmeneguele commented
Really nice work @zampierilucas !! Just do what @prarit mentioned on his comment and the code should be fine.
Thanks for that! Also, it's worthy mentioning this PR should solve issue #147.

2021-07-28 18:10 UTC, bmeneguele commented
@zampierilucas please squash your "Pr suggestions" commit into the first one, the suggestions are direct corrections to what was made in the first, which wasn't merged yet :).

However, it seems you still have one change to do in cmd/issue_note.go:
```diff
-	issueNoteCmd.Flags().Bool("resolve", false,"[unused in issue note command]")
+	issueNoteCmd.Flags().Bool("resolve", false, "[unused in issue note command]")
```

Another issue is:
```
400 {message: {base: [Your issue has been recognized as spam. Please, change the content or solve the reCAPTCHA to proceed.]}}
```

hopefully it'll get solved when you try the build once again.

2021-07-28 19:13 UTC, zampierilucas commented
> @zampierilucas please squash your "Pr suggestions" commit into the first one, the suggestions are direct corrections to what was made in the first, which wasn't merged yet :).
> 
> However, it seems you still have one change to do in cmd/issue_note.go:
> 
> ```diff
> -	issueNoteCmd.Flags().Bool("resolve", false,"[unused in issue note command]")
> +	issueNoteCmd.Flags().Bool("resolve", false, "[unused in issue note command]")
> ```
> 
> Another issue is:
> 
> ```
> 400 {message: {base: [Your issue has been recognized as spam. Please, change the content or solve the reCAPTCHA to proceed.]}}
> ```
> 
> hopefully it'll get solved when you try the build once again.

Sure, I just want to make sure the build passes before squashing it :)  
I'll fix that space issue :p

2021-08-02 19:12 UTC, zaquestion approved these changes

2021-08-04 15:05 UTC, merged